---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: monitor-network
  name: monitor-network
  namespace: openshift-network-metrics
spec:
  endpoints:
    - interval: 10s
      port: metrics
  relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: sourcepod
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: sourcenamespace
  selector:
    matchLabels:
      service: network-metrics-service
  namespaceSelector:
    matchNames:
      - openshift-network-metrics

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    service: network-metrics-service
  name: network-metrics-service
  namespace: openshift-network-metrics
spec:
  selector:
    app: network-metrics-daemon
  #  clusterIP: None
  ports:
    - name: metrics
      port: 9091
      protocol: TCP
      targetPort: 9091
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: openshift-network-metrics
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: openshift-network-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-k8s
  labels:
    prometheus: k8s
spec:
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchLabels:
      name: monitor-network
  version: v1.3.0
